name: Approve Migration

on:
  # pull_request_review:
  #   types: [submitted]
  workflow_dispatch:

jobs:
  bytebase-approve-migration:
    runs-on: ubuntu-latest
    # Runs only if PR is approved and target branch is main
    # if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main'
    if: github.event.review.state == 'approved'
    env:
      ISSUE_TITLE: "[${{ github.repository }}#${{ github.event.pull_request.number }}] ${{ github.event.pull_request.title }}"
    name: Approve Migration
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Bytebase
        id: login
        uses: bytebase/github-action-example/.github/actions/login@main
        with:
          url: ${{ vars.BYTEBASE_URL }}
          service-account: ${{ vars.BYTEBASE_SERVICE_ACCOUNT }}
          service-account-key: ${{ secrets.BYTEBASE_PASSWORD }}
      - name: Approve issue
        id: approve
        uses: bytebase/github-action-example/.github/actions/approve-issue@main
        with:
          url: ${{ vars.BYTEBASE_URL }}
          token: ${{ steps.login.outputs.token }}
          headers: '{"Accept-Encoding": "deflate, gzip"}'
          project-id: ${{ vars.BYTEBASE_PROJECT }}
          title: ${{ env.ISSUE_TITLE }}
          comment: "Approved by CI"