name: Check Migration status

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - "sql/*.sql"

jobs:
  bytebase-check-migration-status:
    runs-on: ubuntu-latest
    env:
      ISSUE_TITLE: "[${{ github.repository }}#${{ github.event.pull_request.number }}] ${{ github.event.pull_request.title }}"
    name: Check Migration Status
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Bytebase
        id: login
        uses: bytebase/github-action-example/.github/actions/login@main
        with:
          url: ${{ vars.BYTEBASE_URL }}
          service-account: ${{ vars.BYTEBASE_SERVICE_ACCOUNT }}
          service-account-key: ${{ secrets.BYTEBASE_PASSWORD }}
      - name: Check Issue Status
        id: check
        uses: bytebase/github-action-example/.github/actions/check-issue-status@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: "sql/*.sql"
          url: ${{ vars.BYTEBASE_URL }}
          token: ${{ steps.login.outputs.token }}
          headers: '{"Accept-Encoding": "deflate, gzip"}'
          project-id: ${{ vars.BYTEBASE_PROJECT }}
          title: ${{ env.ISSUE_TITLE }}