name: SQL Review

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - "sql/*.sql"

jobs:
  bytebase-sql-review:
    runs-on: ubuntu-latest
    name: SQL Review
    environment: ${{ github.event.pull_request.base.ref == 'master' && 'prod' || 'alpha' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Bytebase
        id: login
        uses: bytebase/github-action-example/.github/actions/login@main
        with:
          url: ${{ vars.BYTEBASE_URL }}
          service-account: ${{ vars.BYTEBASE_SERVICE_ACCOUNT }}
          service-account-key: ${{ secrets.BYTEBASE_PASSWORD }}
      - name: Review
        id: review
        uses:  bytebase/github-action-example/.github/actions/sql-review@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: "sql/*.sql"
          url: ${{ vars.BYTEBASE_URL }}
          token: ${{ steps.login.outputs.token }}
          headers: '{"Accept-Encoding": "deflate, gzip"}'
          database: ${{ vars.DATABASE }}